### ISSUE TITLE
Error launch High Sierra (INTEL)

### ISSUE THREAD

**Issue by DIMANRUS** [Qonfused/OSX-Hyper-V#26]
Helo. Could this be related to the processor?
![image](https://github.com/user-attachments/assets/20fd0064-f838-4d45-9c47-44419455c5c4)

**Comment by Qonfused** [comment]
What CPU are you using for this?

If you're using a DEBUG build of the project (which it should by default), you should see an OpenCore log if you mount the EFI virtual disk. It should help verify whether this is a hardware compatibility issue or a bad image.

**Comment by DIMANRUS** [comment]
I use Intel Core i7-11370H

**Comment by Qonfused** [comment]
The recommended CPUID patch in the README is for spoofing as Comet Lake (10th Gen), which only has support from Catalina onwards. Since Comet Lake uses the same Coffee Lake driver, you can try spoofing the CPUID as a Coffee Lake CPU:
```yaml
Kernel:
  Emulate:
    Cpuid1Data: Data | EA060900 00000000 00000000 00000000
    Cpuid1Mask: Data | FFFFFFFF 00000000 00000000 00000000
```
