### ISSUE TITLE
Add csr-active-config in the delete NVRAM section of the config file

### ISSUE THREAD

**Issue by startergo** [Qonfused/OSX-Hyper-V#29]
Without `csr-active-config` present in the delete section the SIP cannot be changed. This is from your project:
>Variables will only be set if not present or deleted. That is, to overwrite an existing variable value, add the variable name to the Delete section. This approach enables the provision of default values until the operating system takes the lead.

**Comment by startergo** [comment]
I would have done it, but unfortunately I don't know how to add a dictionary and an array in the `yml` . it is not in the manual.

**Comment by Qonfused** [comment]
Dictionary (key) entries in YAML end with `:` and array (list) entries begin with `-` characters:
```yaml
NVRAM:
  Delete:
    7C436110-AB2A-4BBB-A880-FE41995C9F82:
      # Overrides the default SIP setting in macOS.
      - csr-active-config
```
