### ISSUE TITLE
AMD CPU Support

### ISSUE THREAD

**Issue by Qonfused** [Qonfused/OSX-Hyper-V#5]
It hasn't been noted anywhere explicitly that AMD CPUs are supported. As is the case for newer Intel CPUs (see #2), the steps for patching AMD CPUs are the same as with bare metal.

Follow the AMD section of the [Dortania Install](https://dortania.github.io/OpenCore-Install-Guide/) guide for your CPU family. However, in addition to the [AMD kernel patches](https://github.com/AMD-OSX/AMD_Vanilla) (for AMD CPU families 15h, 16h, 17h and 19h), the below kernel patch is required for High Sierra and above:

```yml
Kernel:
  Patch:
    - Arch:                 String  | "x86_64"
      Base:                 String  | "_cpu_syscall_init"
      Comment:              String  | "flagers - kill invalid wrmsr | 10.13+"
      Count:                Integer | 3
      Find:                 Data    | "DzA="
      Identifier:           String  | "kernel"
      MaxKernel:            String  | "23.99.99"
      MinKernel:            String  | "17.0.0"
      Replace:              Data    | "kJA="
```

You can also manually add the below plist entry to your config.plist:

<details><summary>Plist entry (file: <a href="https://github.com/Qonfused/OSX-Hyper-V/files/14821955/patch.plist.zip">patch.plist.zip</a>)</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Kernel</key>
    <dict>
        <key>Patch</key>
        <array>
            <dict>
                <key>Arch</key>
                <string>x86_64</string>
                <key>Base</key>
                <string>_cpu_syscall_init</string>
                <key>Comment</key>
                <string>flagers - kill invalid wrmsr | 10.13+</string>
                <key>Count</key>
                <integer>3</integer>
                <key>Enabled</key>
                <true/>
                <key>Find</key>
                <data>DzA=</data>
                <key>Identifier</key>
                <string>kernel</string>
                <key>Limit</key>
                <integer>0</integer>
                <key>Mask</key>
                <data></data>
                <key>MaxKernel</key>
                <string>23.99.99</string>
                <key>MinKernel</key>
                <string>17.0.0</string>
                <key>Replace</key>
                <data>kJA=</data>
                <key>ReplaceMask</key>
                <data></data>
                <key>Skip</key>
                <integer>0</integer>
            </dict>
        </array>
    </dict>
</dict>
</plist>
```

</details>
